// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmwtvdiegfbpvyklanma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtd3R2ZGllZ2ZicHZ5a2xhbm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzAzNDksImV4cCI6MjA2MTc0NjM0OX0.baPm5bWz0VMnB_sQQW_8hmMk0gz2IHTIQ1tCs6Ymu0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);